### ISSUE TITLE
Question for the datasets

### ISSUE THREAD

**Issue by banyedy** [GeoEval/GeoEval#25]
Did you re-annotate the geometry3k dataset yourself? The Diagram descriptions given in your paper are somewhat different from the original data. Yours seems more reasonable.

**Comment by zzli2022** [comment]
​We did not adopt the labeling of InterGPS, but instead utilized the data format of Geometry3K within PGPSNet. For more related information, please refer to PGPSNet Github, PGPSNet, LANS, PGDP Paper.
